global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 5s
scrape_configs:
- job_name: besu
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets: ['10.214.226.143:8008']

