version: '2.2'

services:

  prometheus:
    image: prom/prometheus
    user: root
    ports:
            - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
            chainnet:
              ipv4_address: 172.43.0.101
  grafana:
    image: grafana/grafana
    user: root
    ports:
            - "3300:3000"
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
    networks:
            chainnet:
              ipv4_address: 172.43.0.102


networks:
  chainnet:
   driver: bridge
   ipam:
     config:
     - subnet: 172.43.0.0/24
       gateway: 172.43.0.1

