version: "2.2"
services:   
        nginxnode:
                image: nginx
                volumes:
                 - ./default.conf:/etc/nginx/conf.d/default.conf
                 - ./nginx.conf:/etc/nginx/nginx.conf
                 - ./nginxdata:/var/log/nginx
                hostname: nginxnode
                ports:
                 - "8080:80"
                cpus: 2
                mem_limit: 1000M
                networks:
                  chainnet:
                    ipv4_address: 172.25.0.101

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
        gateway: 172.25.0.1

        

        
